namespace SpicyTemple.Core.Systems.Anim
{
    public enum AnimGoalType
    {
        animate = 0x0,
        animate_loop = 0x1,
        anim_idle = 0x2,
        anim_fidget = 0x3,
        move_to_tile = 0x4,
        run_to_tile = 0x5,
        attempt_move = 0x6,
        move_to_pause = 0x7,
        move_near_tile = 0x8,
        move_near_obj = 0x9,
        move_straight = 0xA,
        attempt_move_straight = 0xB,
        open_door = 0xC,
        attempt_open_door = 0xD,
        unlock_door = 0xE,
        jump_window = 0xF,
        pickup_item = 0x10,
        attempt_pickup = 0x11,
        pickpocket = 0x12,
        attack = 0x13,
        attempt_attack = 0x14,
        talk = 0x15,
        pick_weapon = 0x16,
        chase = 0x17,
        follow = 0x18,
        follow_to_location = 0x19,
        flee = 0x1A,
        throw_spell = 0x1B,
        attempt_spell = 0x1C,
        shoot_spell = 0x1D,
        hit_by_spell = 0x1E,
        hit_by_weapon = 0x1F,

        // this is where the enums start to be off compared to the debug string in the dll
        // (they added dodge and didn't update the list)
        dodge = 0x20,
        dying,
        destroy_obj,
        use_skill_on,
        attempt_use_skill_on,
        skill_conceal,
        projectile,
        throw_item,
        use_object,
        use_item_on_object,
        use_item_on_object_with_skill,
        use_item_on_tile,
        use_item_on_tile_with_skill,
        knockback,
        floating,
        close_door,
        attempt_close_door,
        animate_reverse,
        move_away_from_obj,
        rotate,
        unconceal,
        run_near_tile,
        run_near_obj,
        animate_stunned,
        animate_kneel_magic_hands,
        attempt_move_near,
        knock_down,
        anim_get_up,
        attempt_move_straight_knockback,
        wander,
        wander_seek_darkness,
        use_picklock_skill_on,
        please_move,
        attempt_spread_out,
        animate_door_open,
        animate_door_closed,
        pend_closing_door,
        throw_spell_friendly,
        attempt_spell_friendly,
        animate_loop_fire_dmg,
        attempt_move_straight_spell,
        move_near_obj_combat,
        attempt_move_near_combat,
        use_container,
        throw_spell_w_cast_anim,
        attempt_spell_w_cast_anim,
        throw_spell_w_cast_anim_2ndary,
        back_off_from,
        attempt_use_pickpocket_skill_on,
        use_disable_device_skill_on_data,
        count = 82
    }
}