namespace OpenTemple.Core.Systems.ObjScript
{
    public enum ObjScriptEvent
    {
        Examine = 0,
        Use = 1,
        Destroy = 2,
        Unlock = 3,
        Get = 4,
        Drop = 5,
        Throw = 6,
        Hit = 7,
        Miss = 8,
        Dialog = 9,
        FirstHeartbeat = 10,
        CatchingThiefPc = 11,
        Dying = 12,
        EnterCombat = 13,
        ExitCombat = 14,
        StartCombat = 15,
        EndCombat = 16,
        BuyObject = 17,
        Resurrect = 18,
        Heartbeat = 19,
        LeaderKilling = 20,
        InsertItem = 21,
        WillKos = 22,
        TakingDamage = 23,
        WieldOn = 24,
        WieldOff = 25,
        CritterHits = 26,
        NewSector = 27,
        RemoveItem = 28,
        LeaderSleeping = 29,
        Bust = 30,
        DialogOverride = 31,
        Transfer = 32,
        CaughtThief = 33,
        CriticalHit = 34,
        CriticalMiss = 35,
        Join = 36,
        Disband = 37,
        NewMap = 38,
        Trap = 39,
        TrueSeeing = 40,
        SpellCast = 41,
        UnlockAttempt = 42
    }
}