namespace SpicyTemple.Particles.Params
{

    public enum PartSysParamId : uint {
        emit_accel_X = 0,
        emit_accel_Y = 1,
        emit_accel_Z = 2,
        emit_velVariation_X = 3,
        emit_velVariation_Y = 4,
        emit_velVariation_Z = 5,
        emit_posVariation_X = 6,
        emit_posVariation_Y = 7,
        emit_posVariation_Z = 8,
        emit_yaw = 9,
        emit_pitch = 10,
        emit_roll = 11,
        emit_scale_X = 12,
        emit_scale_Y = 13,
        emit_scale_Z = 14,
        emit_offset_X = 15,
        emit_offset_Y = 16,
        emit_offset_Z = 17,
        emit_init_vel_X = 18,
        emit_init_vel_Y = 19,
        emit_init_vel_Z = 20,
        emit_init_alpha = 21,
        emit_init_red = 22,
        emit_init_green = 23,
        emit_init_blue = 24,
        part_accel_X = 25,
        part_accel_Y = 26,
        part_accel_Z = 27,
        part_velVariation_X = 28,
        part_velVariation_Y = 29,
        part_velVariation_Z = 30,
        part_posVariation_X = 31,
        part_posVariation_Y = 32,
        part_posVariation_Z = 33,
        part_scale_X = 34,
        part_scale_Y = 35,
        part_scale_Z = 36,
        part_yaw = 37,
        part_pitch = 38,
        part_roll = 39,
        part_alpha = 40,
        part_red = 41,
        part_green = 42,
        part_blue = 43,
        part_attractorBlend = 44,
        PARTICLE_PARAM_COUNT
    }
}