using System.Collections.Generic;
using OpenTemple.Core.GameObject;
using OpenTemple.Core.Systems.D20.Conditions.TemplePlus;
using OpenTemple.Core.Systems.Feats;
using OpenTemple.Core.Systems.Spells;

namespace OpenTemple.Core.Systems.D20.Conditions
{
    public static class FeatConditionMapping
    {
        public readonly struct FeatCondition
        {
            public ConditionSpec Condition { get; }
            public int Arg { get; }

            public FeatCondition(ConditionSpec condition)
            {
                Condition = condition;
                Arg = 0;
            }

            public FeatCondition(ConditionSpec condition, int arg)
            {
                Condition = condition;
                Arg = arg;
            }

            public FeatCondition(ConditionSpec condition, SkillId arg)
            {
                Condition = condition;
                Arg = (int) arg;
            }

            public FeatCondition(ConditionSpec condition, WeaponType arg)
            {
                Condition = condition;
                Arg = (int) arg;
            }

            public FeatCondition(ConditionSpec condition, SchoolOfMagic arg)
            {
                Condition = condition;
                Arg = (int) arg;
            }
        }

        public static readonly Dictionary<FeatId, FeatCondition> Mapping = new Dictionary<FeatId, FeatCondition>
        {
            // @formatter:off
            {FeatId.NATURE_SENSE, new FeatCondition(FeatConditions.NatureSense)},
            {FeatId.CRAFT_STAFF, new FeatCondition(FeatConditions.CraftStaff)},
            {FeatId.FORGE_RING, new FeatCondition(FeatConditions.ForgeRing)},
            {FeatId.MONK_DIAMOND_BODY, new FeatCondition(FeatConditions.VenomImmunityDruid)},
            {FeatId.ALERTNESS, new FeatCondition(FeatConditions.Alertness)},
            {FeatId.CLEAVE, new FeatCondition(FeatConditions.Cleave)},
            {FeatId.DEFLECT_ARROWS, new FeatCondition(FeatConditions.DeflectArrows)},
            {FeatId.DODGE, new FeatCondition(FeatConditions.Dodge)},
            {FeatId.COMBAT_EXPERTISE, new FeatCondition(FeatConditions.FeatExpertise)},
            {FeatId.GREAT_CLEAVE, new FeatCondition(FeatConditions.GreatCleave)},
            {FeatId.GREAT_FORTITUDE, new FeatCondition(FeatConditions.GreatFortitude)},
            {FeatId.IMPROVED_CRITICAL_GAUNTLET, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.gauntlet)},
            {FeatId.IMPROVED_CRITICAL_UNARMED_STRIKE_MEDIUM_SIZED_BEING, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.unarmed_strike_medium_sized_being)},
            {FeatId.IMPROVED_CRITICAL_UNARMED_STRIKE_SMALL_BEING, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.unarmed_strike_small_being)},
            {FeatId.IMPROVED_CRITICAL_DAGGER, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.dagger)},
            {FeatId.IMPROVED_CRITICAL_PUNCHING_DAGGER, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.punching_dagger)},
            {FeatId.IMPROVED_CRITICAL_SPIKED_GAUNTLET, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.spiked_gauntlet)},
            {FeatId.IMPROVED_CRITICAL_LIGHT_MACE, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.light_mace)},
            {FeatId.IMPROVED_CRITICAL_SICKLE, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.sickle)},
            {FeatId.IMPROVED_CRITICAL_CLUB, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.club)},
            {FeatId.IMPROVED_CRITICAL_HALFSPEAR, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.shortspear)},
            {FeatId.IMPROVED_CRITICAL_HEAVY_MACE, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.heavy_mace)},
            {FeatId.IMPROVED_CRITICAL_MORNINGSTAR, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.morningstar)},
            {FeatId.IMPROVED_CRITICAL_QUARTERSTAFF, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.quarterstaff)},
            {FeatId.IMPROVED_CRITICAL_SHORTSPEAR, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.spear)},
            {FeatId.IMPROVED_CRITICAL_LIGHT_CROSSBOW, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.light_crossbow)},
            {FeatId.IMPROVED_CRITICAL_DART, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.dart)},
            {FeatId.IMPROVED_CRITICAL_SLING, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.sling)},
            {FeatId.IMPROVED_CRITICAL_HEAVY_CROSSBOW, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.heavy_crossbow)},
            {FeatId.IMPROVED_CRITICAL_JAVELIN, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.javelin)},
            {FeatId.IMPROVED_CRITICAL_THROWING_AXE, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.throwing_axe)},
            {FeatId.IMPROVED_CRITICAL_LIGHT_HAMMER, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.light_hammer)},
            {FeatId.IMPROVED_CRITICAL_HANDAXE, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.handaxe)},
            {FeatId.IMPROVED_CRITICAL_LIGHT_LANCE, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.light_lance)},
            {FeatId.IMPROVED_CRITICAL_LIGHT_PICK, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.light_pick)},
            {FeatId.IMPROVED_CRITICAL_SAP, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.sap)},
            {FeatId.IMPROVED_CRITICAL_SHORT_SWORD, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.short_sword)},
            {FeatId.IMPROVED_CRITICAL_BATTLEAXE, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.battleaxe)},
            {FeatId.IMPROVED_CRITICAL_LIGHT_FLAIL, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.light_flail)},
            {FeatId.IMPROVED_CRITICAL_HEAVY_LANCE, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.heavy_lance)},
            {FeatId.IMPROVED_CRITICAL_LONGSWORD, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.longsword)},
            {FeatId.IMPROVED_CRITICAL_HEAVY_PICK, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.heavy_pick)},
            {FeatId.IMPROVED_CRITICAL_RAPIER, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.rapier)},
            {FeatId.IMPROVED_CRITICAL_SCIMITAR, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.scimitar)},
            {FeatId.IMPROVED_CRITICAL_TRIDENT, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.trident)},
            {FeatId.IMPROVED_CRITICAL_WARHAMMER, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.warhammer)},
            {FeatId.IMPROVED_CRITICAL_FALCHION, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.falchion)},
            {FeatId.IMPROVED_CRITICAL_HEAVY_FLAIL, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.heavy_flail)},
            {FeatId.IMPROVED_CRITICAL_GLAIVE, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.glaive)},
            {FeatId.IMPROVED_CRITICAL_GREATAXE, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.greataxe)},
            {FeatId.IMPROVED_CRITICAL_GREATCLUB, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.greatclub)},
            {FeatId.IMPROVED_CRITICAL_GREATSWORD, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.greatsword)},
            {FeatId.IMPROVED_CRITICAL_GUISARME, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.guisarme)},
            {FeatId.IMPROVED_CRITICAL_HALBERD, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.halberd)},
            {FeatId.IMPROVED_CRITICAL_LONGSPEAR, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.longspear)},
            {FeatId.IMPROVED_CRITICAL_RANSEUR, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.ranseur)},
            {FeatId.IMPROVED_CRITICAL_SCYTHE, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.scythe)},
            {FeatId.IMPROVED_CRITICAL_SHORTBOW, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.shortbow)},
            {FeatId.IMPROVED_CRITICAL_COMPOSITE_SHORTBOW, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.composite_shortbow)},
            {FeatId.IMPROVED_CRITICAL_LONGBOW, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.longbow)},
            {FeatId.IMPROVED_CRITICAL_COMPOSITE_LONGBOW, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.composite_longbow)},
            {FeatId.IMPROVED_CRITICAL_HALFLING_KAMA, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.halfling_kama)},
            {FeatId.IMPROVED_CRITICAL_KUKRI, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.kukri)},
            {FeatId.IMPROVED_CRITICAL_HALFLING_NUNCHAKU, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.halfling_nunchaku)},
            {FeatId.IMPROVED_CRITICAL_HALFLING_SIANGHAM, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.halfling_siangham)},
            {FeatId.IMPROVED_CRITICAL_KAMA, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.kama)},
            {FeatId.IMPROVED_CRITICAL_NUNCHAKU, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.nunchaku)},
            {FeatId.IMPROVED_CRITICAL_SIANGHAM, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.siangham)},
            {FeatId.IMPROVED_CRITICAL_BASTARD_SWORD, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.bastard_sword)},
            {FeatId.IMPROVED_CRITICAL_DWARVEN_WARAXE, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.dwarven_waraxe)},
            {FeatId.IMPROVED_CRITICAL_GNOME_HOOKED_HAMMER, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.gnome_hooked_hammer)},
            {FeatId.IMPROVED_CRITICAL_ORC_DOUBLE_AXE, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.orc_double_axe)},
            {FeatId.IMPROVED_CRITICAL_SPIKE_CHAIN, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.spike_chain)},
            {FeatId.IMPROVED_CRITICAL_DIRE_FLAIL, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.dire_flail)},
            {FeatId.IMPROVED_CRITICAL_TWO_BLADED_SWORD, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.two_bladed_sword)},
            {FeatId.IMPROVED_CRITICAL_DWARVEN_URGROSH, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.dwarven_urgrosh)},
            {FeatId.IMPROVED_CRITICAL_HAND_CROSSBOW, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.hand_crossbow)},
            {FeatId.IMPROVED_CRITICAL_SHURIKEN, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.shuriken)},
            {FeatId.IMPROVED_CRITICAL_WHIP, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.whip)},
            {FeatId.IMPROVED_CRITICAL_REPEATING_CROSSBOW, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.repeating_crossbow)},
            {FeatId.IMPROVED_CRITICAL_NET, new FeatCondition(FeatConditions.ImprovedCritical, WeaponType.net)},
            {FeatId.IMPROVED_INITIATIVE, new FeatCondition(FeatConditions.ImprovedInitiative)},
            {FeatId.IMPROVED_TWO_WEAPON_FIGHTING, new FeatCondition(FeatConditions.ImprovedTwoWeapon)},
            {FeatId.IMPROVED_TWO_WEAPON_FIGHTING_RANGER, new FeatCondition(FeatConditions.ImprovedTwoWeaponRanger)},
            {FeatId.LIGHTNING_REFLEXES, new FeatCondition(FeatConditions.LightingReflexes)},
            {FeatId.MOBILITY, new FeatCondition(FeatConditions.FeatMobility)},
            {FeatId.POINT_BLANK_SHOT, new FeatCondition(FeatConditions.PointBlankShot)},
            {FeatId.POWER_ATTACK, new FeatCondition(FeatConditions.PowerAttack)},
            {FeatId.QUICK_DRAW, new FeatCondition(FeatConditions.QuickDraw)},
            {FeatId.RAPID_SHOT, new FeatCondition(FeatConditions.RapidShot)},
            {FeatId.RANGER_RAPID_SHOT, new FeatCondition(FeatConditions.RapidShotRanger)},
            {FeatId.RUN, new FeatCondition(FeatConditions.Run)},
            {FeatId.SKILL_FOCUS_ALCHEMY, new FeatCondition(FeatConditions.SkillFocus, 0)},
            {FeatId.SKILL_FOCUS_ANIMAL_EMPATHY, new FeatCondition(FeatConditions.SkillFocus, 1)},
            {FeatId.SKILL_FOCUS_APPRAISE, new FeatCondition(FeatConditions.SkillFocus, 2)},
            {FeatId.SKILL_FOCUS_BALANCE, new FeatCondition(FeatConditions.SkillFocus, 3)},
            {FeatId.SKILL_FOCUS_BLUFF, new FeatCondition(FeatConditions.SkillFocus, 4)},
            {FeatId.SKILL_FOCUS_CLIMB, new FeatCondition(FeatConditions.SkillFocus, 5)},
            {FeatId.SKILL_FOCUS_CONCENTRATION, new FeatCondition(FeatConditions.SkillFocus, 6)},
            {FeatId.SKILL_FOCUS_CRAFT, new FeatCondition(FeatConditions.SkillFocus, 7)},
            {FeatId.SKILL_FOCUS_DECIPHER_SCRIPT, new FeatCondition(FeatConditions.SkillFocus, 8)},
            {FeatId.SKILL_FOCUS_DIPLOMACY, new FeatCondition(FeatConditions.SkillFocus, 9)},
            {FeatId.SKILL_FOCUS_DISABLE_DEVICE, new FeatCondition(FeatConditions.SkillFocus, 10)},
            {FeatId.SKILL_FOCUS_DISGUISE, new FeatCondition(FeatConditions.SkillFocus, 11)},
            {FeatId.SKILL_FOCUS_ESCAPE_ARTIST, new FeatCondition(FeatConditions.SkillFocus, 12)},
            {FeatId.SKILL_FOCUS_FORGERY, new FeatCondition(FeatConditions.SkillFocus, 13)},
            {FeatId.SKILL_FOCUS_GATHER_INFORMATION, new FeatCondition(FeatConditions.SkillFocus, 14)},
            {FeatId.SKILL_FOCUS_HANDLE_ANIMAL, new FeatCondition(FeatConditions.SkillFocus, 15)},
            {FeatId.SKILL_FOCUS_HEAL, new FeatCondition(FeatConditions.SkillFocus, 16)},
            {FeatId.SKILL_FOCUS_HIDE, new FeatCondition(FeatConditions.SkillFocus, 17)},
            {FeatId.SKILL_FOCUS_INNUENDO, new FeatCondition(FeatConditions.SkillFocus, 18)},
            {FeatId.SKILL_FOCUS_INTIMIDATE, new FeatCondition(FeatConditions.SkillFocus, 19)},
            {FeatId.SKILL_FOCUS_INTUIT_DIRECTION, new FeatCondition(FeatConditions.SkillFocus, 20)},
            {FeatId.SKILL_FOCUS_JUMP, new FeatCondition(FeatConditions.SkillFocus, 21)},
            {FeatId.SKILL_FOCUS_KNOWLEDGE, new FeatCondition(FeatConditions.SkillFocus, 22)},
            {FeatId.SKILL_FOCUS_LISTEN, new FeatCondition(FeatConditions.SkillFocus, 23)},
            {FeatId.SKILL_FOCUS_MOVE_SILENTLY, new FeatCondition(FeatConditions.SkillFocus, 24)},
            {FeatId.SKILL_FOCUS_OPEN_LOCK, new FeatCondition(FeatConditions.SkillFocus, 25)},
            {FeatId.SKILL_FOCUS_PERFORMANCE, new FeatCondition(FeatConditions.SkillFocus, 26)},
            {FeatId.SKILL_FOCUS_SLIGHT_OF_HAND, new FeatCondition(FeatConditions.SkillFocus, 27)},
            {FeatId.SKILL_FOCUS_PROFESSION, new FeatCondition(FeatConditions.SkillFocus, 28)},
            {FeatId.SKILL_FOCUS_READ_LIPS, new FeatCondition(FeatConditions.SkillFocus, 29)},
            {FeatId.SKILL_FOCUS_RIDE, new FeatCondition(FeatConditions.SkillFocus, 30)},
            {FeatId.SKILL_FOCUS_SCRY, new FeatCondition(FeatConditions.SkillFocus, 31)},
            {FeatId.SKILL_FOCUS_SEARCH, new FeatCondition(FeatConditions.SkillFocus, 32)},
            {FeatId.SKILL_FOCUS_SENSE_MOTIVE, new FeatCondition(FeatConditions.SkillFocus, 33)},
            {FeatId.SKILL_FOCUS_SPEAK_LANGUAGE, new FeatCondition(FeatConditions.SkillFocus, 34)},
            {FeatId.SKILL_FOCUS_SPELLCRAFT, new FeatCondition(FeatConditions.SkillFocus, 35)},
            {FeatId.SKILL_FOCUS_SPOT, new FeatCondition(FeatConditions.SkillFocus, 36)},
            {FeatId.SKILL_FOCUS_SWIM, new FeatCondition(FeatConditions.SkillFocus, 37)},
            {FeatId.SKILL_FOCUS_TUMBLE, new FeatCondition(FeatConditions.SkillFocus, 38)},
            {FeatId.SKILL_FOCUS_USE_MAGIC_DEVICE, new FeatCondition(FeatConditions.SkillFocus, 39)},
            {FeatId.SKILL_FOCUS_USE_ROPE, new FeatCondition(FeatConditions.SkillFocus, 40)},
            {FeatId.SKILL_FOCUS_SURVIVAL, new FeatCondition(FeatConditions.SkillFocus, 41)},
            {FeatId.SPELL_FOCUS_ABJURATION, new FeatCondition(FeatConditions.SpellFocus, 0)},
            {FeatId.SPELL_FOCUS_CONJURATION, new FeatCondition(FeatConditions.SpellFocus, 1)},
            {FeatId.SPELL_FOCUS_DIVINATION, new FeatCondition(FeatConditions.SpellFocus, 2)},
            {FeatId.SPELL_FOCUS_ENCHANTMENT, new FeatCondition(FeatConditions.SpellFocus, 3)},
            {FeatId.SPELL_FOCUS_EVOCATION, new FeatCondition(FeatConditions.SpellFocus, 4)},
            {FeatId.SPELL_FOCUS_ILLUSION, new FeatCondition(FeatConditions.SpellFocus, 5)},
            {FeatId.SPELL_FOCUS_NECROMANCY, new FeatCondition(FeatConditions.SpellFocus, 6)},
            {FeatId.SPELL_FOCUS_TRANSMUTATION, new FeatCondition(FeatConditions.SpellFocus, 7)},
            {FeatId.STUNNING_FIST, new FeatCondition(FeatConditions.featstunningfist, 0)},
            {FeatId.TWO_WEAPON_FIGHTING, new FeatCondition(FeatConditions.TwoWeapon, 0)},
            {FeatId.WEAPON_FINESSE_GAUNTLET, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.gauntlet)},
            {FeatId.WEAPON_FINESSE_UNARMED_STRIKE_MEDIUM_SIZED_BEING, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.unarmed_strike_medium_sized_being)},
            {FeatId.WEAPON_FINESSE_UNARMED_STRIKE_SMALL_BEING, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.unarmed_strike_small_being)},
            {FeatId.WEAPON_FINESSE_DAGGER, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.dagger)},
            {FeatId.WEAPON_FINESSE_PUNCHING_DAGGER, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.punching_dagger)},
            {FeatId.WEAPON_FINESSE_SPIKED_GAUNTLET, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.spiked_gauntlet)},
            {FeatId.WEAPON_FINESSE_LIGHT_MACE, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.light_mace)},
            {FeatId.WEAPON_FINESSE_SICKLE, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.sickle)},
            {FeatId.WEAPON_FINESSE_CLUB, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.club)},
            {FeatId.WEAPON_FINESSE_HALFSPEAR, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.shortspear)},
            {FeatId.WEAPON_FINESSE_HEAVY_MACE, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.heavy_mace)},
            {FeatId.WEAPON_FINESSE_MORNINGSTAR, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.morningstar)},
            {FeatId.WEAPON_FINESSE_QUARTERSTAFF, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.quarterstaff)},
            {FeatId.WEAPON_FINESSE_SHORTSPEAR, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.spear)},
            {FeatId.WEAPON_FINESSE_LIGHT_CROSSBOW, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.light_crossbow)},
            {FeatId.WEAPON_FINESSE_DART, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.dart)},
            {FeatId.WEAPON_FINESSE_SLING, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.sling)},
            {FeatId.WEAPON_FINESSE_HEAVY_CROSSBOW, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.heavy_crossbow)},
            {FeatId.WEAPON_FINESSE_JAVELIN, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.javelin)},
            {FeatId.WEAPON_FINESSE_THROWING_AXE, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.throwing_axe)},
            {FeatId.WEAPON_FINESSE_LIGHT_HAMMER, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.light_hammer)},
            {FeatId.WEAPON_FINESSE_HANDAXE, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.handaxe)},
            {FeatId.WEAPON_FINESSE_LIGHT_LANCE, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.light_lance)},
            {FeatId.WEAPON_FINESSE_LIGHT_PICK, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.light_pick)},
            {FeatId.WEAPON_FINESSE_SAP, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.sap)},
            {FeatId.WEAPON_FINESSE_SHORT_SWORD, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.short_sword)},
            {FeatId.WEAPON_FINESSE_BATTLEAXE, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.battleaxe)},
            {FeatId.WEAPON_FINESSE_LIGHT_FLAIL, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.light_flail)},
            {FeatId.WEAPON_FINESSE_HEAVY_LANCE, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.heavy_lance)},
            {FeatId.WEAPON_FINESSE_LONGSWORD, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.longsword)},
            {FeatId.WEAPON_FINESSE_HEAVY_PICK, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.heavy_pick)},
            {FeatId.WEAPON_FINESSE_RAPIER, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.rapier)},
            {FeatId.WEAPON_FINESSE_SCIMITAR, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.scimitar)},
            {FeatId.WEAPON_FINESSE_TRIDENT, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.trident)},
            {FeatId.WEAPON_FINESSE_WARHAMMER, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.warhammer)},
            {FeatId.WEAPON_FINESSE_FALCHION, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.falchion)},
            {FeatId.WEAPON_FINESSE_HEAVY_FLAIL, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.heavy_flail)},
            {FeatId.WEAPON_FINESSE_GLAIVE, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.glaive)},
            {FeatId.WEAPON_FINESSE_GREATAXE, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.greataxe)},
            {FeatId.WEAPON_FINESSE_GREATCLUB, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.greatclub)},
            {FeatId.WEAPON_FINESSE_GREATSWORD, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.greatsword)},
            {FeatId.WEAPON_FINESSE_GUISARME, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.guisarme)},
            {FeatId.WEAPON_FINESSE_HALBERD, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.halberd)},
            {FeatId.WEAPON_FINESSE_LONGSPEAR, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.longspear)},
            {FeatId.WEAPON_FINESSE_RANSEUR, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.ranseur)},
            {FeatId.WEAPON_FINESSE_SCYTHE, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.scythe)},
            {FeatId.WEAPON_FINESSE_SHORTBOW, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.shortbow)},
            {FeatId.WEAPON_FINESSE_COMPOSITE_SHORTBOW, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.composite_shortbow)},
            {FeatId.WEAPON_FINESSE_LONGBOW, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.longbow)},
            {FeatId.WEAPON_FINESSE_COMPOSITE_LONGBOW, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.composite_longbow)},
            {FeatId.WEAPON_FINESSE_HALFLING_KAMA, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.halfling_kama)},
            {FeatId.WEAPON_FINESSE_KUKRI, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.kukri)},
            {FeatId.WEAPON_FINESSE_HALFLING_NUNCHAKU, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.halfling_nunchaku)},
            {FeatId.WEAPON_FINESSE_HALFLING_SIANGHAM, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.halfling_siangham)},
            {FeatId.WEAPON_FINESSE_KAMA, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.kama)},
            {FeatId.WEAPON_FINESSE_NUNCHAKU, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.nunchaku)},
            {FeatId.WEAPON_FINESSE_SIANGHAM, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.siangham)},
            {FeatId.WEAPON_FINESSE_BASTARD_SWORD, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.bastard_sword)},
            {FeatId.WEAPON_FINESSE_DWARVEN_WARAXE, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.dwarven_waraxe)},
            {FeatId.WEAPON_FINESSE_GNOME_HOOKED_HAMMER, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.gnome_hooked_hammer)},
            {FeatId.WEAPON_FINESSE_ORC_DOUBLE_AXE, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.orc_double_axe)},
            {FeatId.WEAPON_FINESSE_SPIKE_CHAIN, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.spike_chain)},
            {FeatId.WEAPON_FINESSE_DIRE_FLAIL, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.dire_flail)},
            {FeatId.WEAPON_FINESSE_TWO_BLADED_SWORD, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.two_bladed_sword)},
            {FeatId.WEAPON_FINESSE_DWARVEN_URGROSH, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.dwarven_urgrosh)},
            {FeatId.WEAPON_FINESSE_HAND_CROSSBOW, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.hand_crossbow)},
            {FeatId.WEAPON_FINESSE_SHURIKEN, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.shuriken)},
            {FeatId.WEAPON_FINESSE_WHIP, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.whip)},
            {FeatId.WEAPON_FINESSE_REPEATING_CROSSBOW, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.repeating_crossbow)},
            {FeatId.WEAPON_FINESSE_NET, new FeatCondition(FeatConditions.WeaponFinesse, WeaponType.net)},
            {FeatId.WEAPON_FOCUS_GAUNTLET, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.gauntlet)},
            {FeatId.WEAPON_FOCUS_UNARMED_STRIKE_MEDIUM_SIZED_BEING, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.unarmed_strike_medium_sized_being)},
            {FeatId.WEAPON_FOCUS_UNARMED_STRIKE_SMALL_BEING, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.unarmed_strike_small_being)},
            {FeatId.WEAPON_FOCUS_DAGGER, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.dagger)},
            {FeatId.WEAPON_FOCUS_PUNCHING_DAGGER, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.punching_dagger)},
            {FeatId.WEAPON_FOCUS_SPIKED_GAUNTLET, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.spiked_gauntlet)},
            {FeatId.WEAPON_FOCUS_LIGHT_MACE, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.light_mace)},
            {FeatId.WEAPON_FOCUS_SICKLE, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.sickle)},
            {FeatId.WEAPON_FOCUS_CLUB, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.club)},
            {FeatId.WEAPON_FOCUS_HALFSPEAR, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.shortspear)},
            {FeatId.WEAPON_FOCUS_HEAVY_MACE, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.heavy_mace)},
            {FeatId.WEAPON_FOCUS_MORNINGSTAR, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.morningstar)},
            {FeatId.WEAPON_FOCUS_QUARTERSTAFF, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.quarterstaff)},
            {FeatId.WEAPON_FOCUS_SHORTSPEAR, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.spear)},
            {FeatId.WEAPON_FOCUS_LIGHT_CROSSBOW, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.light_crossbow)},
            {FeatId.WEAPON_FOCUS_DART, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.dart)},
            {FeatId.WEAPON_FOCUS_SLING, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.sling)},
            {FeatId.WEAPON_FOCUS_HEAVY_CROSSBOW, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.heavy_crossbow)},
            {FeatId.WEAPON_FOCUS_JAVELIN, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.javelin)},
            {FeatId.WEAPON_FOCUS_THROWING_AXE, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.throwing_axe)},
            {FeatId.WEAPON_FOCUS_LIGHT_HAMMER, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.light_hammer)},
            {FeatId.WEAPON_FOCUS_HANDAXE, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.handaxe)},
            {FeatId.WEAPON_FOCUS_LIGHT_LANCE, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.light_lance)},
            {FeatId.WEAPON_FOCUS_LIGHT_PICK, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.light_pick)},
            {FeatId.WEAPON_FOCUS_SAP, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.sap)},
            {FeatId.WEAPON_FOCUS_SHORT_SWORD, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.short_sword)},
            {FeatId.WEAPON_FOCUS_BATTLEAXE, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.battleaxe)},
            {FeatId.WEAPON_FOCUS_LIGHT_FLAIL, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.light_flail)},
            {FeatId.WEAPON_FOCUS_HEAVY_LANCE, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.heavy_lance)},
            {FeatId.WEAPON_FOCUS_LONGSWORD, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.longsword)},
            {FeatId.WEAPON_FOCUS_HEAVY_PICK, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.heavy_pick)},
            {FeatId.WEAPON_FOCUS_RAPIER, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.rapier)},
            {FeatId.WEAPON_FOCUS_SCIMITAR, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.scimitar)},
            {FeatId.WEAPON_FOCUS_TRIDENT, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.trident)},
            {FeatId.WEAPON_FOCUS_WARHAMMER, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.warhammer)},
            {FeatId.WEAPON_FOCUS_FALCHION, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.falchion)},
            {FeatId.WEAPON_FOCUS_HEAVY_FLAIL, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.heavy_flail)},
            {FeatId.WEAPON_FOCUS_GLAIVE, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.glaive)},
            {FeatId.WEAPON_FOCUS_GREATAXE, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.greataxe)},
            {FeatId.WEAPON_FOCUS_GREATCLUB, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.greatclub)},
            {FeatId.WEAPON_FOCUS_GREATSWORD, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.greatsword)},
            {FeatId.WEAPON_FOCUS_GUISARME, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.guisarme)},
            {FeatId.WEAPON_FOCUS_HALBERD, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.halberd)},
            {FeatId.WEAPON_FOCUS_LONGSPEAR, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.longspear)},
            {FeatId.WEAPON_FOCUS_RANSEUR, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.ranseur)},
            {FeatId.WEAPON_FOCUS_SCYTHE, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.scythe)},
            {FeatId.WEAPON_FOCUS_SHORTBOW, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.shortbow)},
            {FeatId.WEAPON_FOCUS_COMPOSITE_SHORTBOW, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.composite_shortbow)},
            {FeatId.WEAPON_FOCUS_LONGBOW, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.longbow)},
            {FeatId.WEAPON_FOCUS_COMPOSITE_LONGBOW, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.composite_longbow)},
            {FeatId.WEAPON_FOCUS_HALFLING_KAMA, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.halfling_kama)},
            {FeatId.WEAPON_FOCUS_KUKRI, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.kukri)},
            {FeatId.WEAPON_FOCUS_HALFLING_NUNCHAKU, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.halfling_nunchaku)},
            {FeatId.WEAPON_FOCUS_HALFLING_SIANGHAM, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.halfling_siangham)},
            {FeatId.WEAPON_FOCUS_KAMA, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.kama)},
            {FeatId.WEAPON_FOCUS_NUNCHAKU, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.nunchaku)},
            {FeatId.WEAPON_FOCUS_SIANGHAM, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.siangham)},
            {FeatId.WEAPON_FOCUS_BASTARD_SWORD, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.bastard_sword)},
            {FeatId.WEAPON_FOCUS_DWARVEN_WARAXE, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.dwarven_waraxe)},
            {FeatId.WEAPON_FOCUS_GNOME_HOOKED_HAMMER, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.gnome_hooked_hammer)},
            {FeatId.WEAPON_FOCUS_ORC_DOUBLE_AXE, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.orc_double_axe)},
            {FeatId.WEAPON_FOCUS_SPIKE_CHAIN, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.spike_chain)},
            {FeatId.WEAPON_FOCUS_DIRE_FLAIL, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.dire_flail)},
            {FeatId.WEAPON_FOCUS_TWO_BLADED_SWORD, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.two_bladed_sword)},
            {FeatId.WEAPON_FOCUS_DWARVEN_URGROSH, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.dwarven_urgrosh)},
            {FeatId.WEAPON_FOCUS_HAND_CROSSBOW, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.hand_crossbow)},
            {FeatId.WEAPON_FOCUS_SHURIKEN, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.shuriken)},
            {FeatId.WEAPON_FOCUS_WHIP, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.whip)},
            {FeatId.WEAPON_FOCUS_REPEATING_CROSSBOW, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.repeating_crossbow)},
            {FeatId.WEAPON_FOCUS_NET, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.net)},
            {FeatId.WEAPON_FOCUS_GRAPPLE, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.grapple)},
            {FeatId.WEAPON_FOCUS_RAY, new FeatCondition(FeatConditions.WeaponFocus, WeaponType.ray)},
            {FeatId.WEAPON_SPECIALIZATION_GAUNTLET, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.gauntlet)},
            {FeatId.WEAPON_SPECIALIZATION_UNARMED_STRIKE_MEDIUM_SIZED_BEING, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.unarmed_strike_medium_sized_being)},
            {FeatId.WEAPON_SPECIALIZATION_UNARMED_STRIKE_SMALL_BEING, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.unarmed_strike_small_being)},
            {FeatId.WEAPON_SPECIALIZATION_DAGGER, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.dagger)},
            {FeatId.WEAPON_SPECIALIZATION_PUNCHING_DAGGER, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.punching_dagger)},
            {FeatId.WEAPON_SPECIALIZATION_SPIKED_GAUNTLET, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.spiked_gauntlet)},
            {FeatId.WEAPON_SPECIALIZATION_LIGHT_MACE, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.light_mace)},
            {FeatId.WEAPON_SPECIALIZATION_SICKLE, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.sickle)},
            {FeatId.WEAPON_SPECIALIZATION_CLUB, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.club)},
            {FeatId.WEAPON_SPECIALIZATION_HALFSPEAR, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.shortspear)},
            {FeatId.WEAPON_SPECIALIZATION_HEAVY_MACE, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.heavy_mace)},
            {FeatId.WEAPON_SPECIALIZATION_MORNINGSTAR, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.morningstar)},
            {FeatId.WEAPON_SPECIALIZATION_QUARTERSTAFF, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.quarterstaff)},
            {FeatId.WEAPON_SPECIALIZATION_SHORTSPEAR, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.spear)},
            {FeatId.WEAPON_SPECIALIZATION_LIGHT_CROSSBOW, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.light_crossbow)},
            {FeatId.WEAPON_SPECIALIZATION_DART, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.dart)},
            {FeatId.WEAPON_SPECIALIZATION_SLING, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.sling)},
            {FeatId.WEAPON_SPECIALIZATION_HEAVY_CROSSBOW, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.heavy_crossbow)},
            {FeatId.WEAPON_SPECIALIZATION_JAVELIN, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.javelin)},
            {FeatId.WEAPON_SPECIALIZATION_THROWING_AXE, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.throwing_axe)},
            {FeatId.WEAPON_SPECIALIZATION_LIGHT_HAMMER, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.light_hammer)},
            {FeatId.WEAPON_SPECIALIZATION_HANDAXE, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.handaxe)},
            {FeatId.WEAPON_SPECIALIZATION_LIGHT_LANCE, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.light_lance)},
            {FeatId.WEAPON_SPECIALIZATION_LIGHT_PICK, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.light_pick)},
            {FeatId.WEAPON_SPECIALIZATION_SAP, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.sap)},
            {FeatId.WEAPON_SPECIALIZATION_SHORT_SWORD, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.short_sword)},
            {FeatId.WEAPON_SPECIALIZATION_BATTLEAXE, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.battleaxe)},
            {FeatId.WEAPON_SPECIALIZATION_LIGHT_FLAIL, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.light_flail)},
            {FeatId.WEAPON_SPECIALIZATION_HEAVY_LANCE, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.heavy_lance)},
            {FeatId.WEAPON_SPECIALIZATION_LONGSWORD, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.longsword)},
            {FeatId.WEAPON_SPECIALIZATION_HEAVY_PICK, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.heavy_pick)},
            {FeatId.WEAPON_SPECIALIZATION_RAPIER, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.rapier)},
            {FeatId.WEAPON_SPECIALIZATION_SCIMITAR, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.scimitar)},
            {FeatId.WEAPON_SPECIALIZATION_TRIDENT, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.trident)},
            {FeatId.WEAPON_SPECIALIZATION_WARHAMMER, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.warhammer)},
            {FeatId.WEAPON_SPECIALIZATION_FALCHION, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.falchion)},
            {FeatId.WEAPON_SPECIALIZATION_HEAVY_FLAIL, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.heavy_flail)},
            {FeatId.WEAPON_SPECIALIZATION_GLAIVE, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.glaive)},
            {FeatId.WEAPON_SPECIALIZATION_GREATAXE, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.greataxe)},
            {FeatId.WEAPON_SPECIALIZATION_GREATCLUB, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.greatclub)},
            {FeatId.WEAPON_SPECIALIZATION_GREATSWORD, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.greatsword)},
            {FeatId.WEAPON_SPECIALIZATION_GUISARME, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.guisarme)},
            {FeatId.WEAPON_SPECIALIZATION_HALBERD, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.halberd)},
            {FeatId.WEAPON_SPECIALIZATION_LONGSPEAR, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.longspear)},
            {FeatId.WEAPON_SPECIALIZATION_RANSEUR, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.ranseur)},
            {FeatId.WEAPON_SPECIALIZATION_SCYTHE, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.scythe)},
            {FeatId.WEAPON_SPECIALIZATION_SHORTBOW, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.shortbow)},
            {FeatId.WEAPON_SPECIALIZATION_COMPOSITE_SHORTBOW, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.composite_shortbow)},
            {FeatId.WEAPON_SPECIALIZATION_LONGBOW, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.longbow)},
            {FeatId.WEAPON_SPECIALIZATION_COMPOSITE_LONGBOW, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.composite_longbow)},
            {FeatId.WEAPON_SPECIALIZATION_HALFLING_KAMA, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.halfling_kama)},
            {FeatId.WEAPON_SPECIALIZATION_KUKRI, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.kukri)},
            {FeatId.WEAPON_SPECIALIZATION_HALFLING_NUNCHAKU, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.halfling_nunchaku)},
            {FeatId.WEAPON_SPECIALIZATION_HALFLING_SIANGHAM, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.halfling_siangham)},
            {FeatId.WEAPON_SPECIALIZATION_KAMA, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.kama)},
            {FeatId.WEAPON_SPECIALIZATION_NUNCHAKU, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.nunchaku)},
            {FeatId.WEAPON_SPECIALIZATION_SIANGHAM, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.siangham)},
            {FeatId.WEAPON_SPECIALIZATION_BASTARD_SWORD, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.bastard_sword)},
            {FeatId.WEAPON_SPECIALIZATION_DWARVEN_WARAXE, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.dwarven_waraxe)},
            {FeatId.WEAPON_SPECIALIZATION_GNOME_HOOKED_HAMMER, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.gnome_hooked_hammer)},
            {FeatId.WEAPON_SPECIALIZATION_ORC_DOUBLE_AXE, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.orc_double_axe)},
            {FeatId.WEAPON_SPECIALIZATION_SPIKE_CHAIN, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.spike_chain)},
            {FeatId.WEAPON_SPECIALIZATION_DIRE_FLAIL, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.dire_flail)},
            {FeatId.WEAPON_SPECIALIZATION_TWO_BLADED_SWORD, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.two_bladed_sword)},
            {FeatId.WEAPON_SPECIALIZATION_DWARVEN_URGROSH, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.dwarven_urgrosh)},
            {FeatId.WEAPON_SPECIALIZATION_HAND_CROSSBOW, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.hand_crossbow)},
            {FeatId.WEAPON_SPECIALIZATION_SHURIKEN, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.shuriken)},
            {FeatId.WEAPON_SPECIALIZATION_WHIP, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.whip)},
            {FeatId.WEAPON_SPECIALIZATION_REPEATING_CROSSBOW, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.repeating_crossbow)},
            {FeatId.WEAPON_SPECIALIZATION_NET, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.net)},
            {FeatId.WEAPON_SPECIALIZATION_GRAPPLE, new FeatCondition(FeatConditions.WeaponSpecialization, WeaponType.grapple)},
            {FeatId.WHIRLWIND_ATTACK, new FeatCondition(FeatConditions.WhirlwindAttack, 0)},
            {FeatId.TWO_WEAPON_FIGHTING_RANGER, new FeatCondition(FeatConditions.TwoWeaponRanger, 0)},
            {FeatId.VENOM_IMMUNITY, new FeatCondition(FeatConditions.VenomImmunityDruid, 0)},
            {FeatId.UNCANNY_DODGE, new FeatCondition(FeatConditions.UncannyDodge, 0)},
            {FeatId.IMPROVED_UNCANNY_DODGE, new FeatCondition(FeatConditions.ImprovedUncannyDodge, 0)},
            {FeatId.FLURRY_OF_BLOWS, new FeatCondition(FeatConditions.FlurryOfBlows, 0)},
            {FeatId.BARBARIAN_RAGE, new FeatCondition(FeatConditions.BarbarianRage, 0)},
            {FeatId.SNEAK_ATTACK, new FeatCondition(FeatConditions.SneakAttack, 0)},
            {FeatId.STUNNING_ATTACKS, new FeatCondition(FeatConditions.featstunningfist, 0)},
            {FeatId.DIVINE_GRACE, new FeatCondition(FeatConditions.DivineGrace, 0)},
            {FeatId.SMITE_EVIL, new FeatCondition(FeatConditions.SmiteEvil, 0)},
            {FeatId.AURA_OF_COURAGE, new FeatCondition(FeatConditions.AuraofCourage, 0)},
            {FeatId.LAY_ON_HANDS, new FeatCondition(FeatConditions.LayonHands, 0)},
            {FeatId.EVASION, new FeatCondition(FeatConditions.Evasion, 0)},
            {FeatId.IMPROVED_EVASION, new FeatCondition(FeatConditions.ImprovedEvasion, 0)},
            {FeatId.FAST_MOVEMENT, new FeatCondition(FeatConditions.FastMovement, 0)},
            {FeatId.DIVINE_HEALTH, new FeatCondition(FeatConditions.DivineHealth, 0)},
            {FeatId.FAVORED_ENEMY_ABERRATION, new FeatCondition(FeatConditions.FavoredEnemy, 0)},
            {FeatId.FAVORED_ENEMY_ANIMAL, new FeatCondition(FeatConditions.FavoredEnemy, 1)},
            {FeatId.FAVORED_ENEMY_BEAST, new FeatCondition(FeatConditions.FavoredEnemy, 2)},
            {FeatId.FAVORED_ENEMY_CONSTRUCT, new FeatCondition(FeatConditions.FavoredEnemy, 3)},
            {FeatId.FAVORED_ENEMY_DRAGON, new FeatCondition(FeatConditions.FavoredEnemy, 4)},
            {FeatId.FAVORED_ENEMY_ELEMENTAL, new FeatCondition(FeatConditions.FavoredEnemy, 5)},
            {FeatId.FAVORED_ENEMY_FEY, new FeatCondition(FeatConditions.FavoredEnemy, 6)},
            {FeatId.FAVORED_ENEMY_GIANT, new FeatCondition(FeatConditions.FavoredEnemy, 7)},
            {FeatId.FAVORED_ENEMY_MAGICAL_BEAST, new FeatCondition(FeatConditions.FavoredEnemy, 8)},
            {FeatId.FAVORED_ENEMY_MONSTROUS_HUMANOID, new FeatCondition(FeatConditions.FavoredEnemy, 9)},
            {FeatId.FAVORED_ENEMY_OOZE, new FeatCondition(FeatConditions.FavoredEnemy, 10)},
            {FeatId.FAVORED_ENEMY_PLANT, new FeatCondition(FeatConditions.FavoredEnemy, 11)},
            {FeatId.FAVORED_ENEMY_SHAPECHANGER, new FeatCondition(FeatConditions.FavoredEnemy, 12)},
            {FeatId.FAVORED_ENEMY_UNDEAD, new FeatCondition(FeatConditions.FavoredEnemy, 13)},
            {FeatId.FAVORED_ENEMY_VERMIN, new FeatCondition(FeatConditions.FavoredEnemy, 14)},
            {FeatId.FAVORED_ENEMY_OUTSIDER_EVIL, new FeatCondition(FeatConditions.FavoredEnemy, 15)},
            {FeatId.FAVORED_ENEMY_OUTSIDER_GOOD, new FeatCondition(FeatConditions.FavoredEnemy, 16)},
            {FeatId.FAVORED_ENEMY_OUTSIDER_LAWFUL, new FeatCondition(FeatConditions.FavoredEnemy, 17)},
            {FeatId.FAVORED_ENEMY_OUTSIDER_CHAOTIC, new FeatCondition(FeatConditions.FavoredEnemy, 18)},
            {FeatId.FAVORED_ENEMY_HUMANOID_GOBLINOID, new FeatCondition(FeatConditions.FavoredEnemy, 19)},
            {FeatId.FAVORED_ENEMY_HUMANOID_REPTILIAN, new FeatCondition(FeatConditions.FavoredEnemy, 20)},
            {FeatId.FAVORED_ENEMY_HUMANOID_DWARF, new FeatCondition(FeatConditions.FavoredEnemy, 21)},
            {FeatId.FAVORED_ENEMY_HUMANOID_ELF, new FeatCondition(FeatConditions.FavoredEnemy, 22)},
            {FeatId.FAVORED_ENEMY_HUMANOID_GNOLL, new FeatCondition(FeatConditions.FavoredEnemy, 23)},
            {FeatId.FAVORED_ENEMY_HUMANOID_GNOME, new FeatCondition(FeatConditions.FavoredEnemy, 24)},
            {FeatId.FAVORED_ENEMY_HUMANOID_HALFLING, new FeatCondition(FeatConditions.FavoredEnemy, 25)},
            {FeatId.FAVORED_ENEMY_HUMANOID_ORC, new FeatCondition(FeatConditions.FavoredEnemy, 26)},
            {FeatId.FAVORED_ENEMY_HUMANOID_HUMAN, new FeatCondition(FeatConditions.FavoredEnemy, 27)},
            {FeatId.DETECT_EVIL, new FeatCondition(FeatConditions.DetectEvil, 0)},
            {FeatId.KI_STRIKE, new FeatCondition(FeatConditions.KiStrike, 0)},
            {FeatId.DEFENSIVE_ROLL, new FeatCondition(FeatConditions.DefensiveRoll, 0)},
            {FeatId.OPPORTUNIST, new FeatCondition(FeatConditions.Opportunist, 0)},
            {FeatId.STILL_MIND, new FeatCondition(FeatConditions.StillMind, 0)},
            {FeatId.PURITY_OF_BODY, new FeatCondition(FeatConditions.PurityOfBody, 0)},
            {FeatId.REMOVE_DISEASE, new FeatCondition(FeatConditions.RemoveDisease, 0)},
            {FeatId.WHOLENESS_OF_BODY, new FeatCondition(FeatConditions.WholenessofBody, 0)},
            {FeatId.BREW_POTION, new FeatCondition(FeatConditions.BrewPotion, 0)},
            {FeatId.SKILL_MASTERY, new FeatCondition(FeatConditions.SkillMastery, 0)},
            {FeatId.SCRIBE_SCROLL, new FeatCondition(FeatConditions.ScribeScroll, 0)},
            {FeatId.CRAFT_WAND, new FeatCondition(FeatConditions.CraftWand, 0)},
            {FeatId.CRAFT_ROD, new FeatCondition(FeatConditions.CraftRod, 0)},
            {FeatId.CRAFT_WONDROUS_ITEM, new FeatCondition(FeatConditions.CraftWonderousItem, 0)},
            {FeatId.CRAFT_MAGIC_ARMS_AND_ARMOR, new FeatCondition(FeatConditions.CraftMagicArmsandArmor, 0)},
            {FeatId.TRACK, new FeatCondition(FeatConditions.Track, 0)},
            {FeatId.TOUGHNESS, new FeatCondition(FeatConditions.Toughness, 0)},
            {FeatId.ANIMAL_COMPANION, new FeatCondition(FeatConditions.AnimalCompanion, 0)},
            {FeatId.CALL_FAMILIAR, new FeatCondition(FeatConditions.CallFamiliar, 0)},
            {FeatId.ACROBATIC, new FeatCondition(FeatConditions.Acrobatic, 0)},
            {FeatId.INVESTIGATOR, new FeatCondition(FeatConditions.Investigator, 0)},
            {FeatId.MAGICAL_AFFINITY, new FeatCondition(FeatConditions.MagicalAffinity, 0)},
            {FeatId.NEGOTIATOR, new FeatCondition(FeatConditions.Negotiator, 0)},
            {FeatId.NIMBLE_FINGERS, new FeatCondition(FeatConditions.NimbleFingers, 0)},
            {FeatId.PERSUASIVE, new FeatCondition(FeatConditions.Persuasive, 0)},
            {FeatId.SELF_SUFFICIENT, new FeatCondition(FeatConditions.SelfSufficient, 0)},
            {FeatId.STEALTHY, new FeatCondition(FeatConditions.Stealthy, 0)},
            {FeatId.MANYSHOT, new FeatCondition(FeatConditions.ManyShot, 0)},
            {FeatId.RANGER_MANYSHOT, new FeatCondition(FeatConditions.ManyShotRanger, 0)},
            {FeatId.GREATER_SPELL_FOCUS_ABJURATION, new FeatCondition(FeatConditions.GreaterSpellFocus, 0)},
            {FeatId.GREATER_SPELL_FOCUS_CONJURATION, new FeatCondition(FeatConditions.GreaterSpellFocus, 1)},
            {FeatId.GREATER_SPELL_FOCUS_DIVINATION, new FeatCondition(FeatConditions.GreaterSpellFocus, 2)},
            {FeatId.GREATER_SPELL_FOCUS_ENCHANTMENT, new FeatCondition(FeatConditions.GreaterSpellFocus, 3)},
            {FeatId.GREATER_SPELL_FOCUS_EVOCATION, new FeatCondition(FeatConditions.GreaterSpellFocus, 4)},
            {FeatId.GREATER_SPELL_FOCUS_ILLUSION, new FeatCondition(FeatConditions.GreaterSpellFocus, 5)},
            {FeatId.GREATER_SPELL_FOCUS_NECROMANCY, new FeatCondition(FeatConditions.GreaterSpellFocus, 6)},
            {FeatId.GREATER_SPELL_FOCUS_TRANSMUTATION, new FeatCondition(FeatConditions.GreaterSpellFocus, 7)},
            {FeatId.TWO_WEAPON_DEFENSE, new FeatCondition(FeatConditions.TwoWeaponDefense, 0)},
            {FeatId.GREATER_WEAPON_FOCUS_GAUNTLET, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.gauntlet)},
            {FeatId.GREATER_WEAPON_FOCUS_UNARMED_STRIKE_MEDIUM_SIZED_BEING, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.unarmed_strike_medium_sized_being)},
            {FeatId.GREATER_WEAPON_FOCUS_UNARMED_STRIKE_SMALL_BEING, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.unarmed_strike_small_being)},
            {FeatId.GREATER_WEAPON_FOCUS_DAGGER, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.dagger)},
            {FeatId.GREATER_WEAPON_FOCUS_PUNCHING_DAGGER, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.punching_dagger)},
            {FeatId.GREATER_WEAPON_FOCUS_SPIKED_GAUNTLET, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.spiked_gauntlet)},
            {FeatId.GREATER_WEAPON_FOCUS_LIGHT_MACE, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.light_mace)},
            {FeatId.GREATER_WEAPON_FOCUS_SICKLE, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.sickle)},
            {FeatId.GREATER_WEAPON_FOCUS_CLUB, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.club)},
            {FeatId.GREATER_WEAPON_FOCUS_HALFSPEAR, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.shortspear)},
            {FeatId.GREATER_WEAPON_FOCUS_HEAVY_MACE, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.heavy_mace)},
            {FeatId.GREATER_WEAPON_FOCUS_MORNINGSTAR, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.morningstar)},
            {FeatId.GREATER_WEAPON_FOCUS_QUARTERSTAFF, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.quarterstaff)},
            {FeatId.GREATER_WEAPON_FOCUS_SHORTSPEAR, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.spear)},
            {FeatId.GREATER_WEAPON_FOCUS_LIGHT_CROSSBOW, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.light_crossbow)},
            {FeatId.GREATER_WEAPON_FOCUS_DART, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.dart)},
            {FeatId.GREATER_WEAPON_FOCUS_SLING, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.sling)},
            {FeatId.GREATER_WEAPON_FOCUS_HEAVY_CROSSBOW, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.heavy_crossbow)},
            {FeatId.GREATER_WEAPON_FOCUS_JAVELIN, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.javelin)},
            {FeatId.GREATER_WEAPON_FOCUS_THROWING_AXE, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.throwing_axe)},
            {FeatId.GREATER_WEAPON_FOCUS_LIGHT_HAMMER, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.light_hammer)},
            {FeatId.GREATER_WEAPON_FOCUS_HANDAXE, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.handaxe)},
            {FeatId.GREATER_WEAPON_FOCUS_LIGHT_LANCE, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.light_lance)},
            {FeatId.GREATER_WEAPON_FOCUS_LIGHT_PICK, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.light_pick)},
            {FeatId.GREATER_WEAPON_FOCUS_SAP, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.sap)},
            {FeatId.GREATER_WEAPON_FOCUS_SHORT_SWORD, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.short_sword)},
            {FeatId.GREATER_WEAPON_FOCUS_BATTLEAXE, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.battleaxe)},
            {FeatId.GREATER_WEAPON_FOCUS_LIGHT_FLAIL, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.light_flail)},
            {FeatId.GREATER_WEAPON_FOCUS_HEAVY_LANCE, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.heavy_lance)},
            {FeatId.GREATER_WEAPON_FOCUS_LONGSWORD, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.longsword)},
            {FeatId.GREATER_WEAPON_FOCUS_HEAVY_PICK, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.heavy_pick)},
            {FeatId.GREATER_WEAPON_FOCUS_RAPIER, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.rapier)},
            {FeatId.GREATER_WEAPON_FOCUS_SCIMITAR, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.scimitar)},
            {FeatId.GREATER_WEAPON_FOCUS_TRIDENT, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.trident)},
            {FeatId.GREATER_WEAPON_FOCUS_WARHAMMER, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.warhammer)},
            {FeatId.GREATER_WEAPON_FOCUS_FALCHION, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.falchion)},
            {FeatId.GREATER_WEAPON_FOCUS_HEAVY_FLAIL, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.heavy_flail)},
            {FeatId.GREATER_WEAPON_FOCUS_GLAIVE, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.glaive)},
            {FeatId.GREATER_WEAPON_FOCUS_GREATAXE, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.greataxe)},
            {FeatId.GREATER_WEAPON_FOCUS_GREATCLUB, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.greatclub)},
            {FeatId.GREATER_WEAPON_FOCUS_GREATSWORD, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.greatsword)},
            {FeatId.GREATER_WEAPON_FOCUS_GUISARME, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.guisarme)},
            {FeatId.GREATER_WEAPON_FOCUS_HALBERD, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.halberd)},
            {FeatId.GREATER_WEAPON_FOCUS_LONGSPEAR, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.longspear)},
            {FeatId.GREATER_WEAPON_FOCUS_RANSEUR, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.ranseur)},
            {FeatId.GREATER_WEAPON_FOCUS_SCYTHE, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.scythe)},
            {FeatId.GREATER_WEAPON_FOCUS_SHORTBOW, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.shortbow)},
            {FeatId.GREATER_WEAPON_FOCUS_COMPOSITE_SHORTBOW, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.composite_shortbow)},
            {FeatId.GREATER_WEAPON_FOCUS_LONGBOW, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.longbow)},
            {FeatId.GREATER_WEAPON_FOCUS_COMPOSITE_LONGBOW, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.composite_longbow)},
            {FeatId.GREATER_WEAPON_FOCUS_HALFLING_KAMA, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.halfling_kama)},
            {FeatId.GREATER_WEAPON_FOCUS_KUKRI, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.kukri)},
            {FeatId.GREATER_WEAPON_FOCUS_HALFLING_NUNCHAKU, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.halfling_nunchaku)},
            {FeatId.GREATER_WEAPON_FOCUS_HALFLING_SIANGHAM, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.halfling_siangham)},
            {FeatId.GREATER_WEAPON_FOCUS_KAMA, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.kama)},
            {FeatId.GREATER_WEAPON_FOCUS_NUNCHAKU, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.nunchaku)},
            {FeatId.GREATER_WEAPON_FOCUS_SIANGHAM, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.siangham)},
            {FeatId.GREATER_WEAPON_FOCUS_BASTARD_SWORD, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.bastard_sword)},
            {FeatId.GREATER_WEAPON_FOCUS_DWARVEN_WARAXE, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.dwarven_waraxe)},
            {FeatId.GREATER_WEAPON_FOCUS_GNOME_HOOKED_HAMMER, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.gnome_hooked_hammer)},
            {FeatId.GREATER_WEAPON_FOCUS_ORC_DOUBLE_AXE, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.orc_double_axe)},
            {FeatId.GREATER_WEAPON_FOCUS_SPIKE_CHAIN, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.spike_chain)},
            {FeatId.GREATER_WEAPON_FOCUS_DIRE_FLAIL, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.dire_flail)},
            {FeatId.GREATER_WEAPON_FOCUS_TWO_BLADED_SWORD, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.two_bladed_sword)},
            {FeatId.GREATER_WEAPON_FOCUS_DWARVEN_URGROSH, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.dwarven_urgrosh)},
            {FeatId.GREATER_WEAPON_FOCUS_HAND_CROSSBOW, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.hand_crossbow)},
            {FeatId.GREATER_WEAPON_FOCUS_SHURIKEN, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.shuriken)},
            {FeatId.GREATER_WEAPON_FOCUS_WHIP, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.whip)},
            {FeatId.GREATER_WEAPON_FOCUS_REPEATING_CROSSBOW, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.repeating_crossbow)},
            {FeatId.GREATER_WEAPON_FOCUS_NET, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.net)},
            {FeatId.GREATER_WEAPON_FOCUS_GRAPPLE, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.grapple)},
            {FeatId.GREATER_WEAPON_FOCUS_RAY, new FeatCondition(FeatConditions.GreaterWeaponFocus, WeaponType.ray)},
            // TemplePlus Additions/Changes
            {FeatId.MONK_DIAMOND_SOUL, new FeatCondition(TemplePlusFeatConditions.DiamondSoul, 0)},
            {FeatId.MONK_PERFECT_SELF, new FeatCondition(TemplePlusFeatConditions.PerfectSelf, 10)},
            {FeatId.MONK_EMPTY_BODY, new FeatCondition(TemplePlusFeatConditions.EmptyBody, -1)},
            {FeatId.MONK_QUIVERING_PALM, new FeatCondition(TemplePlusFeatConditions.QuiveringPalm, 0)},
            // {FeatId.IMPROVED_TRIP, new FeatCondition(FeatConditions.ImprovedTrip, 0)},
            {FeatId.IMPROVED_TRIP, new FeatCondition(TemplePlusFeatConditions.ImprovedTrip, 0)},
            // {FeatId.WILD_SHAPE, new FeatCondition(FeatConditions.WildShape, 0)},
            {FeatId.WILD_SHAPE, new FeatCondition(Wildshape.FeatCondition, 0)},
            // {FeatId.IRON_WILL, new FeatCondition(FeatConditions.IronWill, 0)},
            {FeatId.IRON_WILL, new FeatCondition(TemplePlusFeatConditions.IronWill, 0)},

            // @formatter:on
        };
    }
}