namespace OpenTemple.Core.Ui.CharSheet.Portrait;

public enum PortraitUiTexture
{
    PortraitBorder = 10,
    EquippedItems = 20,
    Button3dModelDisabled = 30,
    Button3dModelNormal = 31,
    Button3dModelHover = 32,
    Button3dModelPressed = 33,
    Button3dModelSelected = 34,
    ButtonPortraitDisabled = 40,
    ButtonPortraitNormal = 41,
    ButtonPortraitHover = 42,
    ButtonPortraitPressed = 43,
    ButtonPortraitSelected = 44,
    ButtonPaperdollDisabled = 60,
    ButtonPaperdollNormal = 61,
    ButtonPaperdollHover = 62,
    ButtonPaperdollPressed = 63,
    ButtonPaperdollSelected = 64,
    ButtonTabBlueDisabled = 80,
    ButtonTabBlueNormal = 81,
    ButtonTabBlueHover = 82,
    ButtonTabBluePressed = 83,
    ButtonTabBlueSelected = 84,
    ButtonTabGreenDisabled = 100,
    ButtonTabGreenNormal = 101,
    ButtonTabGreenHover = 102,
    ButtonTabGreenPressed = 103,
    ButtonTabGreenSelected = 104,

    ButtonTabPurpleDisabled = 120,
    ButtonTabPurpleNormal = 121,
    ButtonTabPurpleHover = 122,
    ButtonTabPurplePressed = 123,
    ButtonTabPurpleSelected = 124,

    ButtonTabRedDisabled = 140,
    ButtonTabRedNormal = 141,
    ButtonTabRedHover = 142,
    ButtonTabRedPressed = 143,
    ButtonTabRedSelected = 144,

    ButtonTabYellowDisabled = 160,
    ButtonTabYellowNormal = 161,
    ButtonTabYellowHover = 162,
    ButtonTabYellowPressed = 163,
    ButtonTabYellowSelected = 164,

    WeaponHighlightBlue = 180,
    WeaponHighlightGreen = 181,
    WeaponHighlightPurple = 182,
    WeaponHighlightRed = 183,
    WeaponHighlightYellow = 184,
}