namespace OpenTemple.Core.Systems.D20;

public enum SkillId
{
    appraise = 0,
    bluff = 1,
    concentration = 2,
    diplomacy = 3,
    disable_device = 4,
    gather_information = 5,
    heal = 6,
    hide = 7,
    intimidate = 8,
    listen = 9,
    move_silently = 10,
    open_lock = 11,
    pick_pocket = 12,
    search = 13,
    sense_motive = 14,
    spellcraft = 15,
    spot = 16,
    tumble = 17,
    use_magic_device = 18,
    wilderness_lore = 19,
    perform = 20,
    alchemy = 21,
    balance = 22,
    climb = 23,
    craft = 24,
    decipher_script = 25,
    disguise = 26,
    escape_artist = 27,
    forgery = 28,
    handle_animal = 29,
    innuendo = 30,
    intuit_direction = 31,
    jump = 32,
    knowledge_arcana = 33,
    knowledge_religion = 34,
    knowledge_nature = 35,
    knowledge_all = 36,
    profession = 37,
    read_lips = 38,
    ride = 39,
    swim = 40,
    use_rope = 41,

    count // number of skills (for internal use only!)
}