namespace SpicyTemple.Core.Systems.D20
{
    public enum Stat : int
    {
        strength = 0x0,
        dexterity = 0x1,
        constitution = 0x2,
        intelligence = 0x3,
        wisdom = 0x4,
        charisma = 0x5,

        level = 0x6,
        level_barbarian = 0x7,
        level_bard = 0x8,
        level_cleric = 0x9,
        level_druid = 0xA,
        level_fighter = 0xB,
        level_monk = 0xC,
        level_paladin = 0xD,
        level_ranger = 0xE,
        level_rogue = 0xF,
        level_sorcerer = 0x10,
        level_wizard = 0x11,

        level_arcane_archer = 18,
        level_arcane_trickster = 19,
        level_archmage = 20,
        level_assassin = 21,
        level_blackguard = 22,
        level_dragon_disciple = 23,
        level_duelist = 24,
        level_dwarven_defender = 25,
        level_eldritch_knight = 26,
        level_hierophant = 27,
        level_horizon_walker = 28,
        level_loremaster = 29,
        level_mystic_theurge = 30,
        level_shadowdancer = 31,
        level_thaumaturgist = 32,

        level_warlock = 33,
        level_favored_soul = 34,
        level_red_avenger = 35,
        level_iaijutsu_master = 36,
        level_sacred_fist = 37,
        level_stormlord = 38,
        level_elemental_savant = 39,
        level_blood_magus = 40,
        level_beastmaster = 41,
        level_cryokineticist = 42,
        level_frost_mage = 43,
        level_artificer = 44,
        level_abjurant_champion = 45,

        level_psion = 58,
        level_psychic_warrior = 59,
        level_soulknife = 60,
        level_wilder = 61,
        level_cerebmancer = 62,
        level_elocator = 63,
        level_metamind = 64,
        level_psion_uncarnate = 65,
        level_psionic_fist = 66,
        level_pyrokineticist = 67,
        level_slayer = 68,
        level_thrallherd = 69,
        level_war_mind = 70,

        level_crusader = 71,
        level_swordsage = 72,
        level_warblade = 73,
        level_bloodclaw_master = 74,
        level_bloodstorm_blade = 75,
        level_deepstone_sentinel = 76,
        level_eternal_blade = 77,
        level_jade_phoenix_mage = 78,
        level_master_of_nine = 79,
        level_ruby_knight_vindicator = 80,
        level_shadow_sun_ninja = 81,


        hp_max = 0xE4,
        hp_current = 229,
        race = 0xE6,
        category = 0xE7,
        gender = 0xE8,
        age = 0xE9,
        height = 0xEA,
        weight = 0xEB,
        size = 0xEC,
        experience = 0xED,
        alignment = 0xEE,
        deity = 0xEF,
        domain_1 = 0xF0,
        domain_2 = 0xF1,
        alignment_choice = 0xF2,
        favored_enemies = 0xF3,
        known_spells = 0xF4,
        memorized_spells = 0xF5,
        spells_per_day = 0xF6,
        school_specialization = 0xF7,
        school_prohibited = 0xF8,

        money = 249,
        money_pp = 0xFA,
        money_gp = 251,
        money_ep = 0xFC,
        money_sp = 253,
        money_cp = 0xFE,

        str_mod = 255,
        dex_mod = 0x100,
        con_mod = 0x101,
        int_mod = 0x102,
        wis_mod = 0x103,
        cha_mod = 0x104,

        ac = 261,
        initiative_bonus = 0x106,

        save_reflexes = 263,
        save_fortitude = 0x108,
        save_willpower = 0x109,

        attack_bonus = 0x10A,
        damage_bonus = 0x10B,
        carried_weight = 268,
        movement_speed = 0x10D,
        run_speed = 0x10E,
        load = 271,
        subdual_damage = 0x110,

        caster_level = 273,
        caster_level_barbarian = 0x112,
        caster_level_bard = 0x113,
        caster_level_cleric = 0x114,
        caster_level_druid = 0x115,
        caster_level_fighter = 0x116,
        caster_level_monk = 0x117,
        caster_level_paladin = 0x118,
        caster_level_ranger = 0x119,
        caster_level_rogue = 0x11A,
        caster_level_sorcerer = 283,
        caster_level_wizard = 284,

        subrace = 285,

        melee_attack_bonus = 286,
        ranged_attack_bonus = 287,

        spell_list_level = 288, // NEW! used for getting the extended spell lists (modified by PrC's and such)

        psi_points_max = 300,
        psi_points_cur = 301,
        _count // for internal use
    }
}