namespace SpicyTemple.Core.GameObject
{
    public enum WeaponType : uint
    {
        gauntlet = 0,
        unarmed_strike_medium_sized_being = 1,
        unarmed_strike_small_being = 2,
        dagger = 3,
        punching_dagger = 4,
        spiked_gauntlet = 5,
        light_mace = 6,
        sickle = 7,
        club = 8,
        shortspear = 9,
        heavy_mace = 10,
        morningstar = 11,
        quarterstaff = 12,
        spear = 13,
        light_crossbow = 14,		// 14
        dart = 15,
        sling = 16,
        heavy_crossbow = 17,		// 17
        javelin = 18,
        throwing_axe = 19,
        light_hammer = 20,
        handaxe = 21,
        light_lance = 22,
        light_pick = 23,
        sap = 24,
        short_sword = 25,
        battleaxe = 26,
        light_flail = 27,
        heavy_lance = 28,
        longsword = 29,
        heavy_pick = 30,
        rapier = 31,
        scimitar = 32,
        trident = 33,
        warhammer = 34,
        falchion = 35,
        heavy_flail = 36,
        glaive = 37,
        greataxe = 38,
        greatclub = 39,
        greatsword = 40,
        guisarme = 41,
        halberd = 42,
        longspear = 43,  //43
        ranseur = 44,
        scythe = 45,
        shortbow = 46,
        composite_shortbow = 47,
        longbow = 48,
        composite_longbow = 49,
        halfling_kama = 50, // 50
        kukri = 51,
        halfling_nunchaku = 52, //52
        halfling_siangham = 53, //53
        kama = 54, //54
        nunchaku = 55, // 55
        siangham = 56, // 56
        bastard_sword = 57,
        dwarven_waraxe = 58,          // racial weapons - 58 and on
        gnome_hooked_hammer = 59,
        orc_double_axe = 60,
        spike_chain = 61,
        dire_flail = 62,
        two_bladed_sword = 63,
        dwarven_urgrosh = 64,
        hand_crossbow = 65,			// 65
        shuriken = 66,
        whip = 67,
        repeating_crossbow = 68,
        net = 69,
        grapple = 70,
        ray = 71,
        grenade = 72,   // 72
        mindblade = 73,

        none = 0xFFFFffff
    }
}