
name: CI
on: [push]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
        with:
          lfs: true
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v2
        if: github.ref == 'refs/heads/master'
        with:
          token: ${{secrets.github_token}}
          prefix: nightly
      # Authenticates packages to push to GPR
      - uses: actions/setup-dotnet@master
        with:
          source-url: https://nuget.pkg.github.com/GrognardsFromHell/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      ### Create MSIX packages
      - name: Create MSIX Packages and Bundle
        run: .\Launcher\MsixPackage\build.ps1 -version 1.0.0.$env:BUILD_NUMBER
      ### Sign (only if on master branch)
      - name: Create nightly code signing certificate from secret
        run: echo $CODE_SIGNING_PFX | base64 -d - > ./OpenTemple.pfx
        shell: bash
        env:
          CODE_SIGNING_PFX: ${{ secrets.CODE_SIGNING_PFX }}
        if: github.ref == 'refs/heads/master'
      - name: Sign Bundle
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
          cd dist/packages
          SignTool sign /fd SHA256 /a /f ..\..\OpenTemple.pfx /p %CODE_SIGNING_PW% *.msix
          SignTool sign /fd SHA256 /a /f ..\..\OpenTemple.pfx /p %CODE_SIGNING_PW% *.msixbundle
        env:
          CODE_SIGNING_PW: ${{ secrets.CODE_SIGNING_PW }}
        if: github.ref == 'refs/heads/master'
        shell: cmd
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
        if: github.ref == 'refs/heads/master'
      - name: Install OpenStack Swift Client
        run: pip install python-keystoneclient python-swiftclient
        if: github.ref == 'refs/heads/master'
      - name: Upload Nightly Build to OpenStack
        if: github.ref == 'refs/heads/master'
        shell: bash
        run: |
          eval "$OPENSTACK_RC"
          # It's crucial to set the right content types here
          cd dist/packages
          swift upload opentemple-nightlies *
        env:
          OPENSTACK_RC: ${{ secrets.OPENSTACK_RC }}
      ### Always upload the bundle as an artifact, even if not on the master branch (for testing)
      - uses: actions/upload-artifact@v1
        with:
          name: MsixPackages
          path: dist/packages

  # Can currently not build on Linux because of Windows Forms
  # build-linux64:
  #   name: Build (Linux 64-bit)
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #       with:
  #         lfs: true
  #     # Add a Nuget source so that the native libs will be found by dotnet cli
  #     - run: |2
  #         echo '<?xml version="1.0" encoding="utf-8"?>
  #         <configuration>
  #           <packageSources>
  #             <add key="ghp" value="https://nuget.pkg.github.com/GrognardsFromHell/index.json" protocolVersion="3" />
  #           </packageSources>
  #           <packageSourceCredentials>
  #             <ghp>
  #               <add key="Username" value="shartte" />
  #               <add key="ClearTextPassword" value="${{ secrets.GITHUB_TOKEN }}" />
  #             </ghp>
  #           </packageSourceCredentials>
  #         </configuration>' > nuget.config
  #     - run: dotnet publish -c Release -o dist --self-contained --version-suffix ${GITHUB_SHA::8} -r linux-x64 Launcher
  #     - run: tar cfJ a opentemple-linux.tar.xz dist
  #       shell: bash
  #     - uses: actions/upload-artifact@v1
  #       with:
  #         name: opentemple-linux
  #         path: opentemple-linux.tar.xz
  # build-osx:
  #   name: Build (MacOS 64-bit)
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #       with:
  #         lfs: true
  #     # Add a Nuget source so that the native libs will be found by dotnet cli
  #     - run: |2
  #         echo '<?xml version="1.0" encoding="utf-8"?>
  #         <configuration>
  #           <packageSources>
  #             <add key="ghp" value="https://nuget.pkg.github.com/GrognardsFromHell/index.json" protocolVersion="3" />
  #           </packageSources>
  #           <packageSourceCredentials>
  #             <ghp>
  #               <add key="Username" value="shartte" />
  #               <add key="ClearTextPassword" value="${{ secrets.GITHUB_TOKEN }}" />
  #             </ghp>
  #           </packageSourceCredentials>
  #         </configuration>' > nuget.config
  #     # Add a Nuget source so that the native libs will be found by dotnet cli
  #     - run: nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/shartte/index.json" -UserName shartte -Password ${{ secrets.GITHUB_TOKEN }}
  #     - run: dotnet publish -c Release -o dist --self-contained --version-suffix ${GITHUB_SHA::8} -r osx-x64 Launcher
  #     - run: tar cfJ a opentemple-mac.tar.xz dist
  #     - uses: actions/upload-artifact@v1
  #       with:
  #         name: opentemple-mac
  #         path: opentemple-mac.tar.xz
